server:
  port: 8080
spring:
  application:
    name: back-end
  datasource:
    url: jdbc:mysql://localhost:3306/job?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  # config pagination
  #  start page = 1
  data:
    web:
      pageable:
        one-indexed-parameters: true
  # config log
logging:
  level:
    org.springframework.security: DEBUG
# config JWT
manh-nt:
  jwt:
    base64-secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
    # expiration : 1 day (seconds)
    access-token-validity-in-seconds: 8640000
    refresh-token-validity-in-seconds : 8640000
# api version
api:
  prefix: "api/v1"




